language: node_js
node_js:
  - "node"
  - "iojs"
os:
  - linux
  - osx
node_js:
  - '4'
branches:
  only:
    - master
cache:
  directories:
    - client/node_modules
    - node_modules
script: cd client && bash script/travis-build.sh
